# Keras basics

In [2]:
import numpy as np
from numpy import genfromtxt

In [5]:
data = genfromtxt('DATA/bank_note_data.txt',delimiter=',')

In [6]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [8]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [10]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
X = features
y = labels

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

# Standardizing the Data

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler = MinMaxScaler()

In [16]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
scaled_X_train = scaler.transform(X_train)

In [19]:
scaled_X_test = scaler.transform(X_test)

# Building the Network with Keras

In [20]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [21]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

In [22]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [23]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 7s - loss: 0.6749 - acc: 0.5473
Epoch 2/50
 - 0s - loss: 0.6649 - acc: 0.5560
Epoch 3/50
 - 0s - loss: 0.6569 - acc: 0.5441
Epoch 4/50
 - 0s - loss: 0.6494 - acc: 0.5441
Epoch 5/50
 - 0s - loss: 0.6410 - acc: 0.5462
Epoch 6/50
 - 1s - loss: 0.6324 - acc: 0.5865
Epoch 7/50
 - 1s - loss: 0.6223 - acc: 0.5974
Epoch 8/50
 - 0s - loss: 0.6115 - acc: 0.6431
Epoch 9/50
 - 0s - loss: 0.5987 - acc: 0.6779
Epoch 10/50
 - 0s - loss: 0.5859 - acc: 0.7127
Epoch 11/50
 - 0s - loss: 0.5717 - acc: 0.7454
Epoch 12/50
 - 0s - loss: 0.5566 - acc: 0.7606
Epoch 13/50
 - 0s - loss: 0.5403 - acc: 0.7911
Epoch 14/50
 - 0s - loss: 0.5236 - acc: 0.7943
Epoch 15/50
 - 0s - loss: 0.5063 - acc: 0.8161
Epoch 16/50
 - 0s - loss: 0.4889 - acc: 0.8324
Epoch 17/50
 - 0s - loss: 0.4711 - acc: 0.8379
Epoch 18/50
 - 0s - loss: 0.4538 - acc: 0.8585
Epoch 19/50
 - 0s - loss: 0.4368 - acc: 0.8596
Epoch 20/50
 - 0s - loss: 0.4201 - acc: 0.8694
Epoch 21/50
 - 0s - loss: 0.4039 - acc: 0.8814
Epoch 22/50
 - 0s - lo

In [36]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [37]:
model.metrics_names

['loss', 'acc']

# Performance

In [38]:
from sklearn.metrics import confusion_matrix, classification_report

In [39]:
preds = model.predict_classes(scaled_X_test)

In [40]:
confusion_matrix(y_test, preds)

array([[250,  12],
       [  8, 183]], dtype=int64)

In [43]:
print(classification_report(y_test, preds))

             precision    recall  f1-score   support

        0.0       0.97      0.95      0.96       262
        1.0       0.94      0.96      0.95       191

avg / total       0.96      0.96      0.96       453



# Save Model

In [44]:
model.save('first_model.h5')

In [45]:
from keras.models import load_model

In [46]:
nmodel = load_model('first_model.h5')

In [49]:
nmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [83]:
nmodel.predict_classes(np.array([[0.0546, 0.01351, 0.15612, 0.000023]]))

array([[1]])

In [89]:
scaled_X_test.shape

(453, 4)

In [88]:
scaled_X_test

array([[0.33901593, 0.98672618, 0.25725159, 0.08770925],
       [0.87149976, 0.49968721, 0.24864223, 0.87783809],
       [0.36313091, 0.26615931, 0.61570938, 0.78636306],
       ...,
       [0.34094859, 0.59829908, 0.20670283, 0.62481246],
       [0.46263116, 0.28193093, 0.433211  , 0.87783809],
       [0.27145937, 0.58767776, 0.23467465, 0.55967157]])

In [90]:
np.array([[0.0546, 0.01351, 0.15612, 0.000023]]).T

array([[5.4600e-02],
       [1.3510e-02],
       [1.5612e-01],
       [2.3000e-05]])